version: '3'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx_node_app
    restart: always
    ports: 
      - '8080:80'
    depends_on:
      - node_app
    networks:
      - default-network
  
  node_app:
    build:
      context: ./node
    container_name: node_app
    restart: always
    depends_on:
      - mysql_node_app
    networks:
      - default-network

  mysql_node_app:
    build:
      context: ./mysql
    container_name: mysql_node_app
    restart: always
    tty: true
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=db_node
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=node
    networks:
      - default-network

networks:
  default-network:
    driver: bridge